### ISSUE TITLE
Iconografia

### ISSUE THREAD

**Issue by LYK45** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros#3]

**Comment by Felpz18** [comment]
![icone](https://user-images.githubusercontent.com/128707254/235823896-0fd60dc7-c316-4837-8c22-c57d6b108224.jpg)

**Comment by Felpz18** [comment]
![imagem_2023-05-03_222156212](https://user-images.githubusercontent.com/128707254/236087019-f8928eaa-4092-4009-bcbe-de2c2a677ed5.png)

**Comment by Felpz18** [comment]
![icones 2](https://user-images.githubusercontent.com/128707254/236087434-b84d9c41-767c-4433-a4bf-343c9b4385a9.jpg)
