### ISSUE TITLE
Tipografia

### ISSUE THREAD

**Issue by LYK45** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros#4]

**Comment by Felpz18** [comment]
![fonte](https://user-images.githubusercontent.com/128707254/235823948-92de411c-9701-44ad-9ce5-6d68f02d7d3c.jpg)

**Comment by Felpz18** [comment]
![tipografia](https://user-images.githubusercontent.com/128707254/236084617-218c4e02-95d0-472b-96ae-5110444d3049.jpg)

**Comment by Felpz18** [comment]
![design1](https://user-images.githubusercontent.com/128707254/236089723-c0ea5273-61b9-4573-9a68-30b7a91d69f6.jpg)
