### ISSUE TITLE
Registros dos Testes

### ISSUE THREAD

**Issue by LYK45** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros#69]

**Comment by Felpz18** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros/assets/128707254/64cfdd01-a76e-4644-9226-1c4209a87408

**Comment by Felpz18** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros/assets/128707254/6aeec093-c430-4de6-b787-74282feda242

**Comment by Felpz18** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros/assets/128707254/40e01cb6-4139-4ee0-aa76-bb6f12b6cc1e

**Comment by Felpz18** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros/assets/128707254/eed6a8eb-a309-4661-ad2e-83226babb5ef

**Comment by Felpz18** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros/assets/128707254/e06e59bc-493d-4a2a-b758-0b147ff0b827

**Comment by Felpz18** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros/assets/128707254/42e3e08d-f7c8-4480-9d4d-adca77fe44cb

**Comment by Felpz18** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros/assets/128707254/6560eb11-3d25-412b-b9be-253a9ee3cfcf

**Comment by Felpz18** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros/assets/128707254/85c1aa09-9c7c-4eed-8ffd-255e10e403ce

**Comment by Felpz18** [comment]
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-primeiros-socorros/assets/128707254/194fdabd-cd19-486e-9221-3f33dcd9cbfe
